/// Flutter icons BottomNavBarIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavBarIcons
///      fonts:
///       - asset: fonts/BottomNavBarIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomNavBarIcons {
  BottomNavBarIcons._();

  static const _kFontFam = 'BottomNavBarIcons';

  static const IconData tent = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ticket = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData idea = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData spotlight =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fireworks =
      const IconData(0xe808, fontFamily: _kFontFam);
}
